name: Auto Socrates ROM + Pixeldrain + Telegram

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2 curl grep sed

      - name: Get latest socrates ROM
        id: rom
        run: |
          BASE_URL="https://sourceforge.net/projects/xiaomi-eu-multilang-miui-roms/files/xiaomi.eu/HyperOS-STABLE-RELEASES/HyperOS3.0/"
          HTML=$(curl -s "$BASE_URL")
          FILE=$(echo "$HTML" | grep -o 'xiaomi.eu_SOCRATES_OS3[^"]*zip' | sort -V | tail -n 1)

          if [ -z "$FILE" ]; then
            echo "No ROM found"
            exit 1
          fi

          URL="https://netix.dl.sourceforge.net/project/xiaomi-eu-multilang-miui-roms/xiaomi.eu/HyperOS-STABLE-RELEASES/HyperOS3.0/$FILE"

          echo "file=$FILE" >> $GITHUB_OUTPUT
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Download ROM
        run: |
          aria2c -x 16 -s 16 -k 1M --continue=true \
            -o "${{ steps.rom.outputs.file }}" \
            "${{ steps.rom.outputs.url }}"

      - name: Upload to Pixeldrain
        id: pd
        env:
          PD_API_KEY: ${{ secrets.PIXELDRAIN_API_KEY }}
        run: |
          FILE="${{ steps.rom.outputs.file }}"

          RESPONSE=$(curl -s -u ":$PD_API_KEY" -F "file=@${FILE}" https://pixeldrain.com/api/file)
          ID=$(echo "$RESPONSE" | grep -o '"id":"[^"]*"' | cut -d '"' -f4)

          if [ -z "$ID" ]; then
            echo "Upload failed"
            exit 1
          fi

          LINK="https://pixeldrain.com/u/${ID}"
          echo "link=$LINK" >> $GITHUB_OUTPUT

      - name: Send to Telegram
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          FILE="${{ steps.rom.outputs.file }}"
          LINK="${{ steps.pd.outputs.link }}"

          TEXT="<b>📦 New Socrates ROM Available</b>

       📱 <b>File:</b> $FILE
       🔗 <b>Download:</b> <a href=\"$LINK\">Click here</a>"

          curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
            -d chat_id="${CHAT_ID}" \
            -d text="$TEXT" \
            -d parse_mode="HTML"
